// Secure word game module - closure protected
const WordGame = (function() {
    'use strict';

    // Encoded word data
    const _d = 'QUJST0FE,QUNDRVBU,QUNUVUFM,QURWRU5U,QURWSUNF,QUZGSVJN,QUZSQUlE,QUdSRUVE,QU5DSE9S,QU5JTUFM,QU5OVUFM,QU5TV0VS,QU5ZT05F,QU5ZV0FZ,QVBQRUFM,QVBQRUFS,QVJPVU5E,QVJSSVZF,QVJUSVNU,QVNQRUNU,QVNTVVJF,QVRUQUNI,QVRUQUNL,QVRURU5E,QVVUSE9S,QVVUVU1O,QVZFTlVF,QVdBS0VO,QkFDS1VQ,QkFMTE9U,QkFOQU5B,QkFOTkVS,QkFSUkVM,QkFTS0VU,QkFUVExF,QkVBQ09O,QkVBVVRZ,QkVDQU1F,QkVGT1JF,QkVIQUxG,QkVIQVZF,QkVISU5E,QkVMSUVG,QkVMT05H,QkVSTElO,QkVUVEVS,QkVZT05E,QklOQVJZ,QklTSE9Q,QklUVEVS,Qk9SREVS,Qk9SUk9X,Qk9UVExF,Qk9UVE9N,Qk9VR0hU,QlJBTkNI,QlJFQUNI,QlJFQVRI,QlJJREdF,QlJJR0hU,QlJPS0VO,QlJPTlpF,QlJVVEFM,QlVDS0VU,QlVER0VU,QlVSREVO,QlVSRUFV,QlVUVE9O,Q0FNRVJB,Q0FNUFVT,Q0FOQ0VM,Q0FOQ0VS,Q0FOVkFT,Q0FSQk9O,Q0FSRUVS,Q0FSUEVU,Q0FTVExF,Q0FTVUFM,Q0FVR0hU,Q0VOVEVS,Q0VSRUFM,Q0hBTkNF,Q0hBTkdF,Q0hBUEVM,Q0hBUkdF,Q0hPSUNF,Q0hPT1NF,Q0hPU0VO,Q0hST01F,Q0hVUkNI,Q0lORU1B,Q0lSQ0xF,Q0lSQ1VT,Q0xBSU1T,Q0xJRU5U,Q0xJTUFU,Q0xPU0VE,Q0xPU0VS,Q0xPU0VU,Q0xPVEhF,Q0xPVURZ,Q09BUlNF,Q09GRkVF,Q09MVU1O,Q09NQkFU,Q09NSU5H,Q09NTU9O,Q09NUEVM,Q09NUExZ,Q09OQ1VS,Q09STkVS,Q09TTUlD,Q09UVE9O,Q09VTlRZ,Q09VUExF,Q09VUE9O,Q09VUlNF,Q09VU0lO,Q1JBRlRZ,Q1JFQVRF,Q1JFRElU,Q1JJU0lT,Q1JJVElD,Q1JVSVNF,Q1VTVE9N,REFNQUdF,REFOQ0VS,REFOR0VS,REVCQVRF,REVDQURF,REVDRU5U,REVDSURF,REVGRUFU,REVGRU5E,REVGSU5F,REVHUkVF,REVNQU5E,REVOVEFM,REVQTE9Z,REVQVVRZ,REVTRVJU,REVTSUdO,REVTSVJF,REVUQUlM,REVURUNU,REVWSUNF,REVWT1RF,RElBTE9H,RElGRkVS,RElHRVNU,RElOTkVS,RElSRUNU,RElWSURF,RElWSU5F,RE9DS0VS,RE9DVE9S,RE9NQUlO,RE9OQVRF,RE9VQkxF,RFJBV0VS,RFJJVkVO,RFJJVkVS,RFVSSU5H,RUFHTEVT,RUFSTkVE,RUFTSUxZ,RUFUSU5H,RURJVE9S,RUZGRUNU,RUZGT1JU,RUlHSFRI,RUlUSEVS,RUxFVkVO,RU1CQVJL,RU1FUkdF,RU1QSVJF,RU1QTE9Z,RU5BQkxF,RU5ESU5H,RU5EVVJF,RU5FUkdZ,RU5HQUdF,RU5HSU5F,RU5PVUdI,RU5SSUNI,RU5TVVJF,RU5USVJF,RU5USVRZ,RVFVSVRZ,RVNDQVBF,RVNUQVRF,RVRITklD,RVVST1BF,RVZPTFZF,RVhDRUVE,RVhDRVBU,RVhDVVNF,RVhFTVBU,RVhQQU5E,RVhQRUNU,RVhQRVJU,RVhQT1JU,RVhQT1NF,RVhURU5E,RVhURU5U,RkFCUklD,RkFDSUFM,RkFDVE9S,RkFJTEVE,RkFJUkxZ,RkFMTEVO,RkFNSUxZ,RkFNT1VT,RkFUSEVS,RkFVTFRT,RkFWT1VS,RkVNQUxF,RklFUkNF,RklHVVJF,RklMSU5H,RklMVEVS,RklOQUxF,RklOR0VS,RklOSVNI,RklTQ0FM,RkxBVk9S,RkxJR0hU,RkxPUkFM,RkxPV0VS,RkxZSU5H,Rk9MTE9X,Rk9SQklE,Rk9SQ0VE,Rk9SRVNU,Rk9SR0VU,Rk9STUFM,Rk9STUFU,Rk9STUVS,Rk9TVEVS,Rk9VR0hU,Rk9VUlRI,RlJBTkNF,RlJFRVpF,RlJFTkNI,RlJJRU5E,RlJPWkVO,RlVTSU9O,RlVUVVJF,R0FMQVhZ,R0FSQUdF,R0FSREVO,R0FUSEVS,R0VOREVS,R0VOSVVT,R0VOVExF,R0VSTUFO,R0xPQkFM,R09MREVO,R09WRVJO,R1JBVkVM,R1JFRUNF,R1JPVU5E,R1JPV1RI,R1VJTFRZ,R1VJVEFS,SEFDS0VS,SEFQUEVO,SEFSRExZ,SEFUUkVE,SEVBTFRI,SEVBUlRT,SEVBVEVE,SEVBVkVO,SEVJR0hU,SEVMTUVU,SEVSRUJZ,SEVSRUlO,SEVST0VT,SElEREVO,SElHSExZ,SE9ORVNU,SE9OT1VS,SE9QSU5H,SE9SUk9S,SFVNQU5F,SFVNQkxF,SFVOR0VS,SFVOVEVS,SUdOT1JF,SU1QQUNU,SU1QT1JU,SU1QT1NF,SU5DT01F,SU5ERUVE,SU5ET09S,SU5EVUNF,SU5GQU5U,SU5GT1JN,SU5KVVJF,SU5KVVJZ,SU5MSU5F,SU5TRUNU,SU5TRVJU,SU5TSURF,SU5TSVNU,SU5URU5E,SU5URU5U,SU5WRVNU,SU5WSVRF,SU5WT0tF,SU5XQVJE,SVNMQU5E,SVRTRUxG,SkFDS0VU,Sk9JTkVE,SlVOR0xF,SlVOSU9S,S0VSTkVM,S05JR0hU,TEFCT1VS,TEFEREVS,TEFOREVE,TEFQVE9Q,TEFURUxZ,TEFURVNU,TEFUVEVS,TEFVTkNI,TEFXWUVS,TEVBREVS,TEVBR1VF,TEVBUk5U,TEVHQUNZ,TEVHRU5E,TEVOR1RI,TEVTU09O,TEVUVEVS,TElBQkxF,TElLRUxZ,TElORUFS,TElRVUlE,TElTVEVO,TElUVExF,TElWSU5H,TE9DQVRF,TE9DS0VE,TE9ORE9O,TE9ORUxZ,TE9OR0VS,TE9TSU5H,TE9WRUxZ,TFVYVVJZ,TUFJTkxZ,TUFLSU5H,TUFOQUdF,TUFOTkVS,TUFOVUFM,TUFSQkxF,TUFSR0lO,TUFSSU5F,TUFSS0VE,TUFSS0VU,TUFTVEVS,TUFUVEVS,TUFUVVJF,TUVBRE9X,TUVESVVN,TUVNQkVS,TUVNT1JZ,TUVOVEFM,TUVOVE9S,TUVSRUxZ,TUVSR0VS,TUVUSE9E,TUVUUklD,TUlERExF,TUlOSU5H,TUlOVVRF,TUlSUk9S,TUlTRVJZ,TU9CSUxF,TU9ERVJO,TU9ERVNU,TU9ESUZZ,TU9EVUxF,TU9NRU5U,TU9OREFZ,TU9OS0VZ,TU9SVEFM,TU9TVExZ,TU9USEVS,TU9USU9O,TU9USVZF,TU9WSU5H,TVVSREVS,TVVTRVVN,TVVUVUFM,TVlTVElD,TkFNRUxZ,TkFSUk9X,TkFUSU9O,TkFUSVZF,TkFUVVJF,TkVBUkJZ,TkVBUkxZ,TkVFREVE,TkVFRExF,TkVVUkFM,TklDRUxZ,Tk9CT0RZ,Tk9STUFM,Tk9USUNF,Tk9USU9O,Tk9VR0hU,TlVNQkVS,T0JKRUNU,T0JUQUlO,T0NDVVBZ,T0NFQU5T,T0ZGRU5E,T0ZGSUNF,T0ZGU0VU,T05MSU5F,T05XQVJE,T1BFTkVE,T1BFTkVS,T1BFTkxZ,T1BQT1NF,T1BUSU9O,T1JBQ0xF,T1JBTkdF,T1JJR0lO,T1VUUFVU,T1VUU0VU,T1hGT1JE,T1hZR0VO,UEFDS0VE,UEFDS0VU,UEFMQUNF,UEFORUxT,UEFSQURF,UEFSRE9O,UEFSRU5U,UEFSVExZ,UEFTU0VE,UEFURU5U,UEFUUk9M,UEFUUk9O,UEVOQ0lM,UEVPUExF,UEVQUEVS,UEVSSU9E,UEVSTUlU,UEVSU09O,UEhSQVNF,UElDS0VE,UElDTklD,UElSQVRF,UExBQ0VE,UExBTkVU,UExBWUVS,UExFQVNF,UExFREdF,UExFTlRZ,UE9DS0VU,UE9FVFJZ,UE9MSUNF,UE9MSUNZ,UE9MSVNI,UE9SVEFM,UE9TVEVS,UE9UQVRP,UE9URU5U,UE9XREVS,UFJBSVNF,UFJBWUVS,UFJFRkVS,UFJFVFRZ,UFJJRVNU,UFJJTkNF,UFJJU09O,UFJPRklU,UFJPTVBU,UFJPUEVS,UFJPVkVO,UFVCTElD,UFVSRUxZ,UFVSUExF,UFVSU1VF,UFVaWkxF,UFlUSE9O,UkFCQklU,UkFDSUFM,UkFESVVT,UkFJU0VE,UkFORE9N,UkFOR0VS,UkFOS0VE,UkFSRUxZ,UkFUSEVS,UkFUSU5H,UkVBREVS,UkVBTExZ,UkVBU09O,UkVDQUxM,UkVDRU5U,UkVDT1JE,UkVEVUNF,UkVGT1JN,UkVGVUdF,UkVGVU5E,UkVGVVNF,UkVHQVJE,UkVHSU1F,UkVHSU9O,UkVHUkVU,UkVKRUNU,UkVMQVRF,UkVMSUVG,UkVNQUlO,UkVNQVJL,UkVNRURZ,UkVNSU5E,UkVNT1RF,UkVNT1ZF,UkVOREVS,UkVOVEFM,UkVQQUlS,UkVQRUFU,UkVQTEFZ,UkVQT1JU,UkVTQ1VF,UkVTSURF,UkVTSUdO,UkVTSVNU,UkVTT1JU,UkVTVUxU,UkVTVU1F,UkVUQUlM,UkVUQUlO,UkVUSVJF,UkVUVVJO,UkVWRUFM,UkVWSUVX,UkVWSVNF,UkVXQVJE,UklCQk9O,UklDSEVT,UklERExF,UklTSU5H,UklUVUFM,Uk9CVVNU,Uk9DS0VU,Uk9UQVRF,Uk9UVEVO,Uk9XSU5H,UlVCQkVS,UlVMSU5H,UlVNT1VS,UlVTSEVE,U0FDUkVE,U0FGRVRZ,U0FJTE9S,U0FMQVJZ,U0FMTU9O,U0FNUExF,U0FWSU5H,U0FZSU5H,U0NFTklD,U0NIRU1F,U0NIT09M,U0NSRUVO,U0NSSVBU,U0VBUkNI,U0VBU09O,U0VDT05E,U0VDUkVU,U0VDVE9S,U0VDVVJF,U0VFSU5H,U0VMRUNU,U0VMTEVS,U0VOSU9S,U0VOU09S,U0VSSUFM,U0VSSUVT,U0VSVkVE,U0VSVkVS,U0VUVExF,U0VWRVJF,U0hBRE9X,U0hBUEVE,U0hBUkVE,U0hJRUxE,U0hPVUxE,U0hPV0VS,U0hSSU5F,U0lHTkFM,U0lHTkVE,U0lMRU5U,U0lMVkVS,U0lNUExF,U0lNUExZ,U0lOR0xF,U0lTVEVS,U0tFVENI,U0xPR0FO,U01PT1RI,U09DSUFM,U09DS0VU,U09MRUxZ,U09MRU1O,U09MVkVE,U09VUkNF,U09WSUVU,U1BFRUNI,U1BIRVJF,U1BJUklU,U1BPS0VO,U1BSRUFE,U1BSSU5H,U1FVQVJF,U1RBQkxF,U1RBVEVE,U1RBVElD,U1RBVFVF,U1RBVFVT,U1RFQURZ,U1RPTEVO,U1RPUkVT,U1RSQUlO,U1RSQU5E,U1RSRUFN,U1RSRUVU,U1RSRVNT,U1RSSUNU,U1RSSUtF,U1RSSU5H,U1RST0tF,U1RST05H,U1RSVUNU,U1RVRElP,U1VCTUlU,U1VCVVJC,U1VCVExF,U1VEREVO,U1VGRkVS,U1VNTUVS,U1VNTUlU,U1VOREFZ,U1VQUExZ,U1VSRUxZ,U1VSVkVZ,U1dJVENI,U1lNQk9M,U1lOVEFY,U1lTVEVN,VEFCTEVU,VEFDS0xF,VEFDVElD,VEFLSU5H,VEFMRU5U,VEFSR0VU,VEFVR0hU,VEVNUExF,VEVOQU5U,VEVOREVS,VEVSUk9S,VEhBTktT,VEhFT1JZ,VEhFU0lT,VEhJUlRZ,VEhPVUdI,VEhSRUFE,VEhSRUFU,VEhSSUxM,VEhST05F,VEhST1dO,VEhSVVNU,VElDS0VU,VElNQkVS,VElNSU5H,VElTU1VF,VE9XQVJE,VFJBREVS,VFJBR0lD,VFJBVkVM,VFJFQVRZ,VFJFTkRZ,VFJJQkFM,VFJJUExF,VFJPUEhZ,VFJVU1RZ,VFJZSU5H,VFVOTkVM,VFVSS0VZ,VFVSTkVE,VFdFTFZF,VFdFTlRZ,VU5BQkxF,VU5GQUlS,VU5GT0xE,VU5JUVVF,VU5JVEVE,VU5MSUtF,VU5MT0NL,VU5TRUVO,VU5VU0VE,VU5WRUlM,VU5XUkFQ,VVBCRUFU,VVBEQVRF,VVBMT0FE,VVBXQVJE,VVJHRU5U,VVNFRlVM,VkFDQU5U,VkFMTEVZ,VkFSSUVE,VkFTVExZ,VkVDVE9S,VkVORE9S,VkVSQkFM,VkVSSUZZ,VkVTU0VM,VklDVElN,VklFTk5B,VklFV0VS,VklLSU5H,VklPTElO,VklSVFVF,VklTSU9O,VklTVUFM,Vk9MVU1F,Vk9USU5H,Vk9ZQUdF,V0FMS0VE,V0FMTEVU,V0FOREVS,V0FOVEVE,V0FSTUxZ,V0VBTFRI,V0VBUE9O,V0VFS0xZ,V0VJR0hU,V0hPTExZ,V0lDS0VE,V0lERUxZ,V0lER0VU,V0lORE9X,V0lOTkVS,V0lOVEVS,V0lTRE9N,V0laQVJE,V09OREVS,V09PREVO,V09SS0VS,V09SVEhZ,V1JJVEVS,WUVMTE9X,WU9HVVJU,Wk9NQklF,Wk9OSU5H';

    // Private state - the word is NEVER exposed directly
    let _w = null;
    let _g = false;

    // Decode helper
    function _b(s) { return atob(s); }

    // Seeded PRNG (same as before)
    function _r(s) {
        const x = Math.sin(s) * 10000;
        return x - Math.floor(x);
    }

    // Get daily word index
    function _i() {
        const n = new Date();
        const s = new Date(2024, 0, 1);
        const d = Math.floor((n - s) / 86400000);
        const all = _d.split(',');
        return Math.floor(_r(d + 12345) * all.length);
    }

    // Initialize - decode today's word into private variable
    function _init() {
        const all = _d.split(',');
        const idx = _i();
        _w = _b(all[idx]);
    }

    // Get date string
    function _ds() {
        return new Date().toISOString().split('T')[0];
    }

    // Time until midnight
    function _tm() {
        const n = new Date();
        const t = new Date(n);
        t.setDate(t.getDate() + 1);
        t.setHours(0, 0, 0, 0);
        return t - n;
    }

    // Format time
    function _ft(ms) {
        const h = Math.floor(ms / 3600000);
        const m = Math.floor((ms % 3600000) / 60000);
        const s = Math.floor((ms % 60000) / 1000);
        return `${h.toString().padStart(2,'0')}:${m.toString().padStart(2,'0')}:${s.toString().padStart(2,'0')}`;
    }

    // Initialize on module load
    _init();

    // Public API - carefully designed to never leak the word
    return {
        // Check if guess wins (boolean only - no word leak)
        checkWin: function(guess) {
            return guess === _w;
        },

        // Get letter feedback without revealing word
        getLetterFeedback: function(guess) {
            const result = Array(6).fill('absent');
            const target = _w.split('');
            const letters = guess.split('');

            // First pass: correct positions
            for (let i = 0; i < 6; i++) {
                if (letters[i] === target[i]) {
                    result[i] = 'correct';
                    target[i] = null;
                }
            }

            // Second pass: present letters
            for (let i = 0; i < 6; i++) {
                if (result[i] === 'correct') continue;
                const idx = target.indexOf(letters[i]);
                if (idx !== -1) {
                    result[i] = 'present';
                    target[idx] = null;
                }
            }

            return result;
        },

        // Only reveal word AFTER game is over
        revealWord: function() {
            return _g ? _w : '??????';
        },

        // Mark game as over (enables reveal)
        setGameOver: function() {
            _g = true;
        },

        // Check if game over flag is set
        isGameOver: function() {
            return _g;
        },

        // Reset for new day
        reset: function() {
            _g = false;
            _init();
        },

        // Utility functions
        getDateString: _ds,
        getTimeUntilNextWord: _tm,
        formatTime: _ft
    };
})();

// Legacy function aliases for compatibility
function getDateString() { return WordGame.getDateString(); }
function getTimeUntilNextWord() { return WordGame.getTimeUntilNextWord(); }
function formatTime(ms) { return WordGame.formatTime(ms); }
